/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BaBrltj9FWY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <main className="flex flex-col items-center justify-center h-screen bg-[#f0f0f5] dark:bg-[#1a1a2e]">
      <div className="w-full max-w-md p-6 bg-white rounded-lg shadow-lg dark:bg-[#2c2c54]">
        <h1 className="text-2xl font-bold mb-4 text-center text-[#6b5b95]">Expense Tracker</h1>
        <div className="space-y-4">
          <div className="space-y-2">
            <div className="border-b border-[#e6e6e6] dark:border-[#3c3c58] pb-4">
              <h2 className="font-medium text-[#6b5b95]">
                John Doe <span className="text-[#9370db] font-bold">+$153.64</span>
              </h2>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Groceries</span>
                  <span className="font-bold text-[#9370db] text-sm">$50.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Utilities</span>
                  <span className="font-bold text-[#9370db] text-sm">$75.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Dining Out</span>
                  <span className="font-bold text-[#9370db] text-sm">$30.00</span>
                </div>
              </div>
            </div>
            <div className="border-b border-[#e6e6e6] dark:border-[#3c3c58] pb-4">
              <h2 className="font-medium text-[#6b5b95]">
                Jane Smith <span className="text-[#9370db] font-bold">+$16.36</span>
              </h2>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Rent</span>
                  <span className="font-bold text-[#9370db] text-sm">$200.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Utilities</span>
                  <span className="font-bold text-[#9370db] text-sm">$75.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Dining Out</span>
                  <span className="font-bold text-[#9370db] text-sm">$50.00</span>
                </div>
              </div>
            </div>
            <div className="border-b border-[#e6e6e6] dark:border-[#3c3c58] pb-4">
              <h2 className="font-medium text-[#6b5b95]">
                Bob Johnson <span className="text-[#9370db] font-bold">-$58.64</span>
              </h2>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Groceries</span>
                  <span className="font-bold text-[#9370db] text-sm">$75.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Utilities</span>
                  <span className="font-bold text-[#9370db] text-sm">$75.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Entertainment</span>
                  <span className="font-bold text-[#9370db] text-sm">$100.00</span>
                </div>
              </div>
            </div>
            <div className="border-b border-[#e6e6e6] dark:border-[#3c3c58] pb-4">
              <h2 className="font-medium text-[#6b5b95]">
                Alice Williams <span className="text-[#9370db] font-bold">+$16.36</span>
              </h2>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Rent</span>
                  <span className="font-bold text-[#9370db] text-sm">$200.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Groceries</span>
                  <span className="font-bold text-[#9370db] text-sm">$50.00</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6b5b95]">Dining Out</span>
                  <span className="font-bold text-[#9370db] text-sm">$75.00</span>
                </div>
              </div>
            </div>
          </div>
          <div className="border-t border-[#e6e6e6] dark:border-[#3c3c58] pt-4">
            <form className="space-y-4">
              <div className="flex items-center gap-2">
                <Input
                  className="flex-1 border-[#e6e6e6] dark:border-[#3c3c58] bg-[#f0f0f5] dark:bg-[#2c2c54] text-[#6b5b95]"
                  placeholder="Add Expense"
                  type="text"
                />
                <Button className="bg-[#9370db] hover:bg-[#8258fa] text-white">Add</Button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </main>
  )
}
